// port-lint: source libc/src/unix/linux_like/linux/arch/generic/mod.rs
package io.github.kotlinmania.libc.unix.linuxlike.linux.arch.generic

import io.github.kotlinmania.libc.*

public data class Termios2(
    val cIflag: TcflagT,
    val cOflag: TcflagT,
    val cCflag: TcflagT,
    val cLflag: TcflagT,
    val cLine: CcT,
    val cCc: List<CcT>,
    val cIspeed: SpeedT,
    val cOspeed: SpeedT,
)

public const val SOL_SOCKET: CInt = 1
public const val SO_DEBUG: CInt = 1
public const val SO_REUSEADDR: CInt = 2
public const val SO_TYPE: CInt = 3
public const val SO_ERROR: CInt = 4
public const val SO_DONTROUTE: CInt = 5
public const val SO_BROADCAST: CInt = 6
public const val SO_SNDBUF: CInt = 7
public const val SO_RCVBUF: CInt = 8
public const val SO_KEEPALIVE: CInt = 9
public const val SO_OOBINLINE: CInt = 10
public const val SO_NO_CHECK: CInt = 11
public const val SO_PRIORITY: CInt = 12
public const val SO_LINGER: CInt = 13
public const val SO_BSDCOMPAT: CInt = 14
public const val SO_REUSEPORT: CInt = 15
public const val SO_PASSCRED: CInt = 16
public const val SO_PEERCRED: CInt = 17
public const val SO_RCVLOWAT: CInt = 18
public const val SO_SNDLOWAT: CInt = 19
public const val SO_SECURITY_AUTHENTICATION: CInt = 22
public const val SO_SECURITY_ENCRYPTION_TRANSPORT: CInt = 23
public const val SO_SECURITY_ENCRYPTION_NETWORK: CInt = 24
public const val SO_BINDTODEVICE: CInt = 25
public const val SO_ATTACH_FILTER: CInt = 26
public const val SO_DETACH_FILTER: CInt = 27
public const val SO_GET_FILTER: CInt = SO_ATTACH_FILTER
public const val SO_PEERNAME: CInt = 28
public val SO_TIMESTAMP: CInt = SO_TIMESTAMP_NEW
public val SO_TIMESTAMPNS: CInt = SO_TIMESTAMPNS_NEW
public val SO_TIMESTAMPING: CInt = SO_TIMESTAMPING_NEW
public val SO_RCVTIMEO: CInt = SO_RCVTIMEO_NEW
public val SO_SNDTIMEO: CInt = SO_SNDTIMEO_NEW
public const val SO_ACCEPTCONN: CInt = 30
public const val SO_PEERSEC: CInt = 31
public const val SO_SNDBUFFORCE: CInt = 32
public const val SO_RCVBUFFORCE: CInt = 33
public const val SO_PASSSEC: CInt = 34
public const val SO_MARK: CInt = 36
public const val SO_PROTOCOL: CInt = 38
public const val SO_DOMAIN: CInt = 39
public const val SO_RXQ_OVFL: CInt = 40
public const val SO_WIFI_STATUS: CInt = 41
public const val SCM_WIFI_STATUS: CInt = SO_WIFI_STATUS
public const val SO_PEEK_OFF: CInt = 42
public const val SO_NOFCS: CInt = 43
public const val SO_LOCK_FILTER: CInt = 44
public const val SO_SELECT_ERR_QUEUE: CInt = 45
public const val SO_BUSY_POLL: CInt = 46
public const val SO_MAX_PACING_RATE: CInt = 47
public const val SO_BPF_EXTENSIONS: CInt = 48
public const val SO_INCOMING_CPU: CInt = 49
public const val SO_ATTACH_BPF: CInt = 50
public const val SO_DETACH_BPF: CInt = SO_DETACH_FILTER
public const val SO_ATTACH_REUSEPORT_CBPF: CInt = 51
public const val SO_ATTACH_REUSEPORT_EBPF: CInt = 52
public const val SO_CNX_ADVICE: CInt = 53
public const val SCM_TIMESTAMPING_OPT_STATS: CInt = 54
public const val SO_MEMINFO: CInt = 55
public const val SO_INCOMING_NAPI_ID: CInt = 56
public const val SO_COOKIE: CInt = 57
public const val SCM_TIMESTAMPING_PKTINFO: CInt = 58
public const val SO_PEERGROUPS: CInt = 59
public const val SO_ZEROCOPY: CInt = 60
public const val SO_TXTIME: CInt = 61
public const val SCM_TXTIME: CInt = SO_TXTIME
public const val SO_BINDTOIFINDEX: CInt = 62
public const val SO_TIMESTAMP_NEW: CInt = 63
public const val SO_TIMESTAMPNS_NEW: CInt = 64
public const val SO_TIMESTAMPING_NEW: CInt = 65
public const val SO_RCVTIMEO_NEW: CInt = 66
public const val SO_SNDTIMEO_NEW: CInt = 67
public const val SO_DETACH_REUSEPORT_BPF: CInt = 68
public const val SO_PREFER_BUSY_POLL: CInt = 69
public const val SO_BUSY_POLL_BUDGET: CInt = 70
public const val SO_NETNS_COOKIE: CInt = 71
public const val SO_BUF_LOCK: CInt = 72
public const val SO_RESERVE_MEM: CInt = 73
public const val SO_TXREHASH: CInt = 74
public const val SO_RCVMARK: CInt = 75
public const val SO_PASSPIDFD: CInt = 76
public const val SO_PEERPIDFD: CInt = 77
public const val SO_DEVMEM_LINEAR: CInt = 78
public const val SO_DEVMEM_DMABUF: CInt = 79
public const val SO_DEVMEM_DONTNEED: CInt = 80
public val SCM_TIMESTAMP: CInt = SO_TIMESTAMP
public val SCM_TIMESTAMPNS: CInt = SO_TIMESTAMPNS
public val SCM_TIMESTAMPING: CInt = SO_TIMESTAMPING
public const val SCM_DEVMEM_LINEAR: CInt = SO_DEVMEM_LINEAR
public const val SCM_DEVMEM_DMABUF: CInt = SO_DEVMEM_DMABUF
public const val TCGETS: Ioctl = 0x5401.toInt()
public const val TCSETS: Ioctl = 0x5402.toInt()
public const val TCSETSW: Ioctl = 0x5403.toInt()
public const val TCSETSF: Ioctl = 0x5404.toInt()
public const val TCGETA: Ioctl = 0x5405.toInt()
public const val TCSETA: Ioctl = 0x5406.toInt()
public const val TCSETAW: Ioctl = 0x5407.toInt()
public const val TCSETAF: Ioctl = 0x5408.toInt()
public const val TCSBRK: Ioctl = 0x5409.toInt()
public const val TCXONC: Ioctl = 0x540A.toInt()
public const val TCFLSH: Ioctl = 0x540B.toInt()
public const val TIOCEXCL: Ioctl = 0x540C.toInt()
public const val TIOCNXCL: Ioctl = 0x540D.toInt()
public const val TIOCSCTTY: Ioctl = 0x540E.toInt()
public const val TIOCGPGRP: Ioctl = 0x540F.toInt()
public const val TIOCSPGRP: Ioctl = 0x5410.toInt()
public const val TIOCOUTQ: Ioctl = 0x5411.toInt()
public const val TIOCSTI: Ioctl = 0x5412.toInt()
public const val TIOCGWINSZ: Ioctl = 0x5413.toInt()
public const val TIOCSWINSZ: Ioctl = 0x5414.toInt()
public const val TIOCMGET: Ioctl = 0x5415.toInt()
public const val TIOCMBIS: Ioctl = 0x5416.toInt()
public const val TIOCMBIC: Ioctl = 0x5417.toInt()
public const val TIOCMSET: Ioctl = 0x5418.toInt()
public const val TIOCGSOFTCAR: Ioctl = 0x5419.toInt()
public const val TIOCSSOFTCAR: Ioctl = 0x541A.toInt()
public const val FIONREAD: Ioctl = 0x541B.toInt()
public const val TIOCINQ: Ioctl = FIONREAD
public const val TIOCLINUX: Ioctl = 0x541C.toInt()
public const val TIOCCONS: Ioctl = 0x541D.toInt()
public const val TIOCGSERIAL: Ioctl = 0x541E.toInt()
public const val TIOCSSERIAL: Ioctl = 0x541F.toInt()
public const val TIOCPKT: Ioctl = 0x5420.toInt()
public const val FIONBIO: Ioctl = 0x5421.toInt()
public const val TIOCNOTTY: Ioctl = 0x5422.toInt()
public const val TIOCSETD: Ioctl = 0x5423.toInt()
public const val TIOCGETD: Ioctl = 0x5424.toInt()
public const val TCSBRKP: Ioctl = 0x5425.toInt()
public const val TIOCSBRK: Ioctl = 0x5427.toInt()
public const val TIOCCBRK: Ioctl = 0x5428.toInt()
public const val TIOCGSID: Ioctl = 0x5429.toInt()
public const val TCGETS2: Ioctl = 0x802c542a.toInt()
public const val TCSETS2: Ioctl = 0x402c542b.toInt()
public const val TCSETSW2: Ioctl = 0x402c542c.toInt()
public const val TCSETSF2: Ioctl = 0x402c542d.toInt()
public const val TIOCGRS485: Ioctl = 0x542E.toInt()
public const val TIOCSRS485: Ioctl = 0x542F.toInt()
public const val TIOCGPTN: Ioctl = 0x80045430.toInt()
public const val TIOCSPTLCK: Ioctl = 0x40045431.toInt()
public const val TIOCGDEV: Ioctl = 0x80045432.toInt()
public const val TCGETX: Ioctl = 0x5432.toInt()
public const val TCSETX: Ioctl = 0x5433.toInt()
public const val TCSETXF: Ioctl = 0x5434.toInt()
public const val TCSETXW: Ioctl = 0x5435.toInt()
public const val TIOCSIG: Ioctl = 0x40045436.toInt()
public const val TIOCVHANGUP: Ioctl = 0x5437.toInt()
public const val TIOCGPKT: Ioctl = 0x80045438.toInt()
public const val TIOCGPTLCK: Ioctl = 0x80045439.toInt()
public const val TIOCGEXCL: Ioctl = 0x80045440.toInt()
public const val TIOCGPTPEER: Ioctl = 0x5441.toInt()
public const val TIOCGISO7816: Ioctl = 0x80285442.toInt()
public const val TIOCSISO7816: Ioctl = 0xc0285443.toInt()
public const val FIONCLEX: Ioctl = 0x5450.toInt()
public const val FIOCLEX: Ioctl = 0x5451.toInt()
public const val FIOASYNC: Ioctl = 0x5452.toInt()
public const val TIOCSERCONFIG: Ioctl = 0x5453.toInt()
public const val TIOCSERGWILD: Ioctl = 0x5454.toInt()
public const val TIOCSERSWILD: Ioctl = 0x5455.toInt()
public const val TIOCGLCKTRMIOS: Ioctl = 0x5456.toInt()
public const val TIOCSLCKTRMIOS: Ioctl = 0x5457.toInt()
public const val TIOCSERGSTRUCT: Ioctl = 0x5458.toInt()
public const val TIOCSERGETLSR: Ioctl = 0x5459.toInt()
public const val TIOCSERGETMULTI: Ioctl = 0x545A.toInt()
public const val TIOCSERSETMULTI: Ioctl = 0x545B.toInt()
public const val TIOCMIWAIT: Ioctl = 0x545C.toInt()
public const val TIOCGICOUNT: Ioctl = 0x545D.toInt()
public const val BLKIOMIN: Ioctl = 0x1278.toInt()
public const val BLKIOOPT: Ioctl = 0x1279.toInt()
public const val BLKSSZGET: Ioctl = 0x1268.toInt()
public const val BLKPBSZGET: Ioctl = 0x127B.toInt()
public const val FIOQSIZE: Ioctl = 0x545E.toInt()
public const val TIOCM_LE: CInt = 0x001
public const val TIOCM_DTR: CInt = 0x002
public const val TIOCM_RTS: CInt = 0x004
public const val TIOCM_ST: CInt = 0x008
public const val TIOCM_SR: CInt = 0x010
public const val TIOCM_CTS: CInt = 0x020
public const val TIOCM_CAR: CInt = 0x040
public const val TIOCM_CD: CInt = TIOCM_CAR
public const val TIOCM_RNG: CInt = 0x080
public const val TIOCM_RI: CInt = TIOCM_RNG
public const val TIOCM_DSR: CInt = 0x100
public const val BOTHER: SpeedT = 4096u
public const val IBSHIFT: TcflagT = 16u
public const val IUCLC: TcflagT = 512u
public const val XCASE: TcflagT = 4u
public const val RLIMIT_CPU: RlimitResourceT = 0.toInt()
public const val RLIMIT_FSIZE: RlimitResourceT = 1.toInt()
public const val RLIMIT_DATA: RlimitResourceT = 2.toInt()
public const val RLIMIT_STACK: RlimitResourceT = 3.toInt()
public const val RLIMIT_CORE: RlimitResourceT = 4.toInt()
public const val RLIMIT_RSS: RlimitResourceT = 5.toInt()
public const val RLIMIT_NPROC: RlimitResourceT = 6.toInt()
public const val RLIMIT_NOFILE: RlimitResourceT = 7.toInt()
public const val RLIMIT_MEMLOCK: RlimitResourceT = 8.toInt()
public const val RLIMIT_AS: RlimitResourceT = 9.toInt()
public const val RLIMIT_LOCKS: RlimitResourceT = 10.toInt()
public const val RLIMIT_SIGPENDING: RlimitResourceT = 11.toInt()
public const val RLIMIT_MSGQUEUE: RlimitResourceT = 12.toInt()
public const val RLIMIT_NICE: RlimitResourceT = 13.toInt()
public const val RLIMIT_RTPRIO: RlimitResourceT = 14.toInt()
public const val RLIMIT_RTTIME: RlimitResourceT = 15.toInt()
public const val RLIM_NLIMITS: CInt = 16
public const val RLIMIT_NLIMITS: RlimitResourceT = RLIM_NLIMITS
public const val RLIM_INFINITY: RlimT = 0xFFFFFFFFFFFFFFFFuL
