// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "SwiftTestHarness",
    dependencies: [
        .package(name: "Libc", path: "../build/SPMPackage/macosArm64/Debug")
    ],
    targets: [
        .testTarget(
            name: "SwiftTestHarnessTests",
            dependencies: [
                .product(name: "LibcLibrary", package: "Libc")
            ],
            linkerSettings: [
                // The SPM Package generated by Kotlin's embedSwiftExportForXcode
                // task contains Swift wrapper sources and C bridge declarations,
                // but the actual symbol implementations (`__root____getExceptionMessage__...`)
                // live in `libLibc.a` produced by the
                // `linkSwiftExportBinaryDebugStaticMacosArm64` /
                // `mergeMacosDebugSwiftExportLibraries` chain. Xcode wires that
                // archive into its own link step via BUILT_PRODUCTS_DIR; a
                // standalone `swift test` invocation has to point at it
                // explicitly. The archive landed at
                // `<repo>/build/swift-test/libLibc.a` when the embed task ran
                // with the macOS Xcode-style environment variables.
                .unsafeFlags([
                    "-L", "../build/swift-test",
                    "-lLibc",
                ]),
            ]
        ),
    ]
)
